# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: PseudoTown API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        clean: true

    - name: Set up .env file
      run: echo "DB_KEY=${{ secrets.DB_KEY }}" > .env

    - name: Set up Docker Compose
      run: |
        docker compose up -d --build
        sleep 10

    - name: API server health check
      run: |
        response_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/hc)
        
        if [ $response_code -eq 200 ]; then
          echo "API server is healthy (HTTP $response_code)"
        else
          echo "API server is not healthy (HTTP $response_code)"
          exit 1
        fi
